version: '3'

volumes:
  pgsql_data: { }

networks:
  frontend:
    driver: bridge
  backend:
    driver: overlay
    attachable: true

services:
  postgresql:
    image: postgres:17.5-alpine3.22
    container_name: schola_blog_postgresql
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DATABASE
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - pgsql_data:/var/lib/postgresql
    networks:
      - backend
  app:
    container_name: schola_blog_node
    environment:
      - DATABASE_HOST=postgresql
      - DATABASE_USER=$POSTGRES_USER
      - DATABASE_PASSWORD=$POSTGRES_PASSWORD
      - DATABASE_NAME=$POSTGRES_DATABASE
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DATABASE}
    depends_on:
      - postgresql
    ports:
      - "$NODE_LOCAL_PORT:$NODE_DOCKER_PORT"
    restart: always
    build: ./node_image
    networks:
      - backend
      - frontend
    command:
      - ./run_app.sh